.catalog:
  name: "Owncloud Test version"
  version: "rancher"
  description: "owncloud test version"
  uuid: owncloudtest-0
  minimum_rancher_version: v1.0.0
  questions:
    - variable: "port"
      label: "Port"
      description: "Your Server Port"
      required: true
      type: "int"
      default: 80

    - variable: "owncloud_ver"
      label: "ownCloud Version"
      description: |
        Please select the version of owncloud.
      type: "enum"
      default: latest
      options:
        - latest
        - 9.1.1
        - 9.1.1-fpm
        - 9.0.5
        - 9.0.5-fpm
        - 8.2.8
        - 8.2.8-fpm
        - 8.1.10
        - 8.1.10-fpm
        - 8.0.15
        - 8.0.15-fpm

owncloud:
